env:
  node: true
  browser: true
  es6: true
  jest: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
settings:
  react:
    version: detect
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - 2
    - single
    - avoidEscape: true
  semi:
    - error
    - never
  react/prop-types:
    - 0
